// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhosHome.Server.Data;

#nullable disable

namespace WhosHome.Server.Data.Migrations
{
    [DbContext(typeof(WhosHomeContext))]
    [Migration("20260806134835_AddReportSpeed")]
    partial class AddReportSpeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("WhosHome.Server.Data.DeviceSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("WhosHome.Server.Data.NotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriberPersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectPersonId");

                    b.HasIndex("SubscriberPersonId", "SubjectPersonId")
                        .IsUnique();

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("WhosHome.Server.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("REAL");

                    b.Property<long?>("LastSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginCode")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LoginCodeExpiresUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SetupToken")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SetupTokenExpiresUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StationarySinceUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("SetupToken");

                    b.ToTable("People");
                });

            modelBuilder.Entity("WhosHome.Server.Data.PositionReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("REAL");

                    b.Property<double?>("BatteryPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<double?>("MovedMeters")
                        .HasColumnType("REAL");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceivedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReportedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SpeedMetersPerSecond")
                        .HasColumnType("REAL");

                    b.Property<double?>("TravelSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "ReceivedUtc");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("WhosHome.Server.Data.DeviceSubscription", b =>
                {
                    b.HasOne("WhosHome.Server.Data.Person", "Person")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WhosHome.Server.Data.NotificationPreference", b =>
                {
                    b.HasOne("WhosHome.Server.Data.Person", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectPersonId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("WhosHome.Server.Data.Person", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("WhosHome.Server.Data.PositionReport", b =>
                {
                    b.HasOne("WhosHome.Server.Data.Person", "Person")
                        .WithMany("Reports")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WhosHome.Server.Data.Person", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
